// Generated by gencpp from file aic_auto_dock/gui_way2ActionGoal.msg
// DO NOT EDIT!


#ifndef AIC_AUTO_DOCK_MESSAGE_GUI_WAY2ACTIONGOAL_H
#define AIC_AUTO_DOCK_MESSAGE_GUI_WAY2ACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <aic_auto_dock/gui_way2Goal.h>

namespace aic_auto_dock
{
template <class ContainerAllocator>
struct gui_way2ActionGoal_
{
  typedef gui_way2ActionGoal_<ContainerAllocator> Type;

  gui_way2ActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  gui_way2ActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::aic_auto_dock::gui_way2Goal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct gui_way2ActionGoal_

typedef ::aic_auto_dock::gui_way2ActionGoal_<std::allocator<void> > gui_way2ActionGoal;

typedef boost::shared_ptr< ::aic_auto_dock::gui_way2ActionGoal > gui_way2ActionGoalPtr;
typedef boost::shared_ptr< ::aic_auto_dock::gui_way2ActionGoal const> gui_way2ActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aic_auto_dock

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'aic_auto_dock': ['/home/aicrobo/catkin_ws/src/aic_auto_dock/obj-x86_64-linux-gnu/devel/share/aic_auto_dock/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98c4e32f163d22f50a9b0ae31a89bc79";
  }

  static const char* value(const ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98c4e32f163d22f5ULL;
  static const uint64_t static_value2 = 0x0a9b0ae31a89bc79ULL;
};

template<class ContainerAllocator>
struct DataType< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aic_auto_dock/gui_way2ActionGoal";
  }

  static const char* value(const ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
gui_way2Goal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: aic_auto_dock/gui_way2Goal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string              tag_no\n\
int32               type\n\
geometry_msgs/Pose  pose\n\
float32             vel_line\n\
float32             vel_angle\n\
float32             back_dist\n\
float32             obstacle_dist\n\
float32             preparePosition\n\
float32             scale            #角速度响应比例，取值范围：0~0.1\n\
\n\
int32               BACK = 0\n\
int32               STRAIGHT = 1\n\
int32               PAUSE = 2\n\
int32               RESUM = 3\n\
int32               INITPORT = 4\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gui_way2ActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aic_auto_dock::gui_way2ActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::aic_auto_dock::gui_way2Goal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIC_AUTO_DOCK_MESSAGE_GUI_WAY2ACTIONGOAL_H
