// Generated by gencpp from file aic_auto_dock/gui_way2Result.msg
// DO NOT EDIT!


#ifndef AIC_AUTO_DOCK_MESSAGE_GUI_WAY2RESULT_H
#define AIC_AUTO_DOCK_MESSAGE_GUI_WAY2RESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aic_auto_dock
{
template <class ContainerAllocator>
struct gui_way2Result_
{
  typedef gui_way2Result_<ContainerAllocator> Type;

  gui_way2Result_()
    : err_msg(0)
    , result(0)
    , remaining_distance(0.0)  {
    }
  gui_way2Result_(const ContainerAllocator& _alloc)
    : err_msg(0)
    , result(0)
    , remaining_distance(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _err_msg_type;
  _err_msg_type err_msg;

   typedef int32_t _result_type;
  _result_type result;

   typedef float _remaining_distance_type;
  _remaining_distance_type remaining_distance;



  enum {
    CANCLE = 1,
    SUCCESS = 2,
    FAILED = 3,
    INITFAILED = 4,
  };


  typedef boost::shared_ptr< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> const> ConstPtr;

}; // struct gui_way2Result_

typedef ::aic_auto_dock::gui_way2Result_<std::allocator<void> > gui_way2Result;

typedef boost::shared_ptr< ::aic_auto_dock::gui_way2Result > gui_way2ResultPtr;
typedef boost::shared_ptr< ::aic_auto_dock::gui_way2Result const> gui_way2ResultConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aic_auto_dock::gui_way2Result_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aic_auto_dock

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'aic_auto_dock': ['/home/aicrobo/catkin_ws/src/aic_auto_dock/obj-x86_64-linux-gnu/devel/share/aic_auto_dock/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e81f05ebaf1c3c2557540a3cd981a074";
  }

  static const char* value(const ::aic_auto_dock::gui_way2Result_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe81f05ebaf1c3c25ULL;
  static const uint64_t static_value2 = 0x57540a3cd981a074ULL;
};

template<class ContainerAllocator>
struct DataType< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aic_auto_dock/gui_way2Result";
  }

  static const char* value(const ::aic_auto_dock::gui_way2Result_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
uint64              err_msg          #状态码\n\
\n\
int32               result\n\
int32               CANCLE = 1\n\
int32               SUCCESS = 2\n\
int32               FAILED = 3\n\
int32               INITFAILED = 4\n\
\n\
float32             remaining_distance\n\
";
  }

  static const char* value(const ::aic_auto_dock::gui_way2Result_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.err_msg);
      stream.next(m.result);
      stream.next(m.remaining_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gui_way2Result_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aic_auto_dock::gui_way2Result_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aic_auto_dock::gui_way2Result_<ContainerAllocator>& v)
  {
    s << indent << "err_msg: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.err_msg);
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "remaining_distance: ";
    Printer<float>::stream(s, indent + "  ", v.remaining_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIC_AUTO_DOCK_MESSAGE_GUI_WAY2RESULT_H
