(cl:defpackage aic_auto_dock-msg
  (:use )
  (:export
   "<GUI_WAY2ACTION>"
   "GUI_WAY2ACTION"
   "<GUI_WAY2ACTIONFEEDBACK>"
   "GUI_WAY2ACTIONFEEDBACK"
   "<GUI_WAY2ACTIONGOAL>"
   "GUI_WAY2ACTIONGOAL"
   "<GUI_WAY2ACTIONRESULT>"
   "GUI_WAY2ACTIONRESULT"
   "<GUI_WAY2FEEDBACK>"
   "GUI_WAY2FEEDBACK"
   "<GUI_WAY2GOAL>"
   "GUI_WAY2GOAL"
   "<GUI_WAY2RESULT>"
   "GUI_WAY2RESULT"
  ))

