set(_CATKIN_CURRENT_PACKAGE "aic_auto_dock")
set(aic_auto_dock_VERSION "0.0.7")
set(aic_auto_dock_MAINTAINER "aicrobo <aicrobo@todo.todo>")
set(aic_auto_dock_PACKAGE_FORMAT "2")
set(aic_auto_dock_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "aic_msgs" "tf" "actionlib" "actionlib_msgs" "aic_laser_feature_line_extraction" "message_runtime" "teb_local_planner")
set(aic_auto_dock_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "aic_msgs" "tf" "actionlib" "actionlib_msgs" "aic_laser_feature_line_extraction" "message_runtime")
set(aic_auto_dock_BUILDTOOL_DEPENDS "catkin")
set(aic_auto_dock_BUILDTOOL_EXPORT_DEPENDS )
set(aic_auto_dock_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "aic_msgs" "tf" "actionlib" "actionlib_msgs" "aic_laser_feature_line_extraction" "message_runtime" "teb_local_planner")
set(aic_auto_dock_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "aic_msgs" "tf" "actionlib" "actionlib_msgs" "aic_laser_feature_line_extraction" "message_runtime" "teb_local_planner")
set(aic_auto_dock_TEST_DEPENDS )
set(aic_auto_dock_DOC_DEPENDS )
set(aic_auto_dock_URL_WEBSITE "")
set(aic_auto_dock_URL_BUGTRACKER "")
set(aic_auto_dock_URL_REPOSITORY "")
set(aic_auto_dock_DEPRECATED "")